### ISSUE TITLE
请问老板，如何备份

### ISSUE THREAD

**Issue by senggai** [machsix/Super-preloader#100]
谢谢

**Comment by machsix** [comment]
备份什么？

**Comment by senggai** [comment]
备份对某个网站是否启用翻页的设置。这样换机换系统时，比较方便。

**Comment by machsix** [comment]
每个站点的数据是存在了[localStorage](https://developer.mozilla.org/zh-CN/docs/Web/API/Window/localStorage)里，要想备份只能一个网站一个网站的手动来
chrome可以用https://chrome.google.com/webstore/detail/localstorage-manager/fkhoimdhngkiicbjobkinobjkoefhkap?hl=en-US
其他的可以用https://todvora.github.io/localstorage-backup/

暂时没计划在脚本里添加类似功能

**Comment by senggai** [comment]
ok 谢谢老板
