### ISSUE TITLE
右上角的红绿灯又不见了

### ISSUE THREAD

**Issue by operammm** [machsix/Super-preloader#110]
今天脚本自动更新了，还能自动翻页，但是右上角的红绿灯没了。
记得以前出过这个毛病，好像被大佬修复了，现在又不见了……
我把脚本删了，换成旧版6.6.6也不显示，原先用6.6.6好好的。好奇怪啊。囧
难道红绿灯按钮的图标依赖的不是本地文件？

火狐60 暴力猴 脚本版本6.6.78

**Comment by machsix** [comment]
![Screenshot from 2019-11-07 15-33-56](https://user-images.githubusercontent.com/28209092/68425413-0c27f200-0174-11ea-8a32-6b129cf848fc.png)

红绿灯的开关是由存在本地的数据，`floatWindow`后面的值决定

你可以在暴力猴里直接改，也可以直接更新到最新版6.6.81， 我在面板里新添加了个重置按钮

面版可以从暴力猴的下面打开，前提是你在一个被脚本支持的网站，比如百度google啥的，gayhub不行

**Comment by operammm** [comment]
@machsix 谢谢大佬详尽的说明。辛苦了。
虽然红绿灯按钮很丑，但是很实用。不见了有点慌。升到6.6.81问题解决了。👍
