### ISSUE TITLE
SITEINFO_JSON

### ISSUE THREAD

**Issue by machsix** [machsix/Super-preloader#13]
一个想法，每次匹配到一个站点并且运行成功后，把站点规则存到localStorage里
然后每次匹配规则先检测localStorage
- 如果检测到就不把SITEINFO_JSON读到内存里了，直接运行
- 如果检测到但脚本运行失败就清空localStorage重新匹配

但一个问题是更新完规则怎么办。。

**Comment by yfdyh000** [comment]
> 如果检测到但脚本运行失败就清空localStorage重新匹配

是怎样的失败，概率有多少，如何判断是临时（包括网页结构不同）还是永久性。更新问题同上。

> 如果检测到就不把SITEINFO_JSON读到内存里了，直接运行

我的想法是更新时直接存，每次使用时直接读，不用全局变量（用完自动销毁），或者给所有正常或异常终止（`return`）处加上变量清空。
