### ISSUE TITLE
How to re enable super preloader?

### ISSUE THREAD

**Issue by pongsatond** [machsix/Super-preloader#1305]
**Describe the bug**

I accidently tick out the enable button and it disappeared forever
No way to re enable it even with delete the script and re installed it

**To Reproduce**
1. Go any website
2. Tick out the enable option
3. It disappeared from that website and no way to undo it

**Expected behavior**
I expect it to have some way to re enable it again

**Screenshots**
![image](https://github.com/user-attachments/assets/1119c309-5f71-467d-ba91-c02d56753714)

**Desktop (please complete the following information):**
 - Brave Browser
 - Version 1.73.97 Chromium: 131.0.6778.108 (Official Build) (64-bit)
 -  Tampermonkey V.5.3.2
 - Ublock Origin
 - Script version: 7.0.17

**Additional context**
 - Have you tried to reset the script following [link](https://greasyfork.org/en/scripts/33522-super-preloaderplus-one-new/discussions/33898)
 - How? Please tell me because uninstall and reinstall doesn't work. 
![image](https://github.com/user-attachments/assets/abe3e85d-2f98-4249-b41f-e1194b792bf8)

**Comment by Killogy** [comment]
Go the the website and open **Inspector** by pressing **Ctrl + Shift + I** keys combination or Right-click on the page and select "Inspect" from the context menu.

Press on **Storage** tab and select **Local Storage**then delete the cookie containing **spfwset** cookie. Refresh the website and script will enable again

![image](https://github.com/user-attachments/assets/65fcf0a4-3be3-4829-9aa9-5c6039d596bf)

**Comment by pongsatond** [comment]
Thank you.
