### ISSUE TITLE
破坏凤舞文学网

### ISSUE THREAD

**Issue by ivysrono** [machsix/Super-preloader#159]
https://www.okma.net/html/345/345366/136202701.shtml
https://m.okma.net/html/345/345366/136202701.shtml

桌面版和移动版都是，一旦翻页脚本运作就上下全白。
Firefox 72
Violentmonkey

**Comment by machsix** [comment]
没发现这样的问题

**Comment by ivysrono** [comment]
需要启用翻页模式

**Comment by ivysrono** [comment]
#196
