### ISSUE TITLE
Error on bellingcat.com

### ISSUE THREAD

**Issue by xinhuang** [machsix/Super-preloader#212]
Dear Developers,

First of all, thank you very much for developing this project!

There is a problem with it enabled globally and while viewing [bellingcat.com](http://bellingcat.com) (See the screenshot attached below)

I am using Firefox 76.0 with Tampermonkey v4.10.6112 and Super_preloaderPlus_one_New 6.13.2.

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/1063783/81253436-8b36ae00-9063-11ea-831b-45763542f6ae.png">

Can you please take a look? Thanks!

Best regards,

**Comment by machsix** [comment]
![Untitled](https://user-images.githubusercontent.com/28209092/81263881-7bd94580-900e-11ea-8453-aaeb237f49e6.png)
Disable it
