### ISSUE TITLE
Removing lazy-load img data-attribute can be problematic

### ISSUE THREAD

**Issue by narcolepticinsomniac** [machsix/Super-preloader#221]
Not sure if the reverse is true, but I wouldn't guess it would be. In some cases, apparently, when the site looks for the attribute, it rebreaks the `src` you just fixed.

Example: [WSHH](https://www.worldstarhiphop.com/videos/)

Rule:

```
  {
    "name": "WSHH",
    "url": "^https?://(www\\.)?worldstarhiphop\\.com.*",
    "pageElement": "css;#main>section:not([class])",
    "exampleUrl": "https://worldstarhiphop.com/videos",
    "nextLink": "css;a.next"
  }
```

Deleting [this line](https://github.com/machsix/Super-preloader/blob/master/src/index.js#L2882) resolves the issue.

Great project, btw. =)

**Comment by machsix** [comment]
With the rule you provided and factory settings, I didn't find any issue on `Edge Chromium+Tampermonkey` or `Firefox+Violentmonkey`. The only problem I see is `span.comments` doesn't show a number because they are dynamically added. 

Could you please provide your test environment and the issue you find?

**Comment by narcolepticinsomniac** [comment]
Since you couldn't repro, I double-checked, and this was my own doing. I have another script I completely forgot about forcing lazy load images to load, which was obviously not counting on the attribute not being there.

I suppose if my script could break it, others could too, so if there's not a good reason to remove them maybe you shouldn't. Or maybe that's just me trying to justify filing an issue for a conflict I should've figured out beforehand. =)
