### ISSUE TITLE
[Suggestion] Utilize GM_openInTab instead of using [target="_blank"]

### ISSUE THREAD

**Issue by narcolepticinsomniac** [machsix/Super-preloader#222]
Add data-attribute to parents and check whether clicked links are inside of it. The API avoids having to whitelist countless individual sites in popup blockers. As a bonus, you can circumvent click hijacking redirects by implementing it similarly to [this](https://greasyfork.org/en/scripts/12367-open-links-in-new-tab/code).

**Comment by machsix** [comment]
I don't understand why I need this API. The script doesn't open new tabs. Maybe you can point out the lines this API is needed?

**Comment by narcolepticinsomniac** [comment]
You're adding `target="_blank"` to links in loaded elements, because what kind of monster wants to lose their place on an infinite scroll list when clicking a link, right? I'm saying that method will get blocked by most decent popup blockers, forcing you to whitelist sites constantly. At least, that's what I'm running into. 

The API has no such issues. The method in the script I linked has the bonus of preventing sites like google from hijacking clicks and redirecting, since it grabs the actual href, prevents click, and opens via the API.

Maybe you don't need it, but it'd be an improvement.

**Comment by machsix** [comment]
I think you are talking about https://github.com/machsix/Super-preloader/blob/5cf85c07557a54efe9cfa82f38a18a5bd22f53bb/src/index.js#L1465-L1474

Thanks for the suggestion. I'll add it later. I'm curious what blocker you use. I use ublock origin and didn't experience this kind of issue.

**Comment by narcolepticinsomniac** [comment]
https://add0n.com/popup-blocker.html


"Prevent page redirection for 2 seconds after a popup is requested" option is pretty sweet for malicious scripts which redirect the current page when they detect blocked popups.
