### ISSUE TITLE
newIframe entry in custom rules not applied

### ISSUE THREAD

**Issue by narcolepticinsomniac** [machsix/Super-preloader#223]
So I set [craigslist](https://newyork.craigslist.org/search/zip?) to use iframes because pics weren't loading, which worked, but some images are slideshows when hovered, which weren't working. 

`newIframe` doc says "in some cases there is a miracle", which is true, because clicking the checkbox in settings, makes these little slide image elements functional. Clicking the checkbox only sets local storage, so I tried to set it in custom settings, but it's like it doesn't register.

Tested in a clean profile this time. Maybe I'm doing something wrong though. Is there a syntax issue?

```
[
  {
    "name": "craigslist",
    "url": "^https?://(.*\\.)?craigslist\\.org.*",
    "pageElement": "css;ul.rows",
    "exampleUrl": "https://newyork.craigslist.org/search/zip",
    "useiframe": true,
    "newIframe": true,
    "nextLink": "css;.bottom .next"
  }
]
```

**Comment by machsix** [comment]
`newIframe` should be wrapped in `autopager`, like the following
```json
 {
    "name": "craigslist",
    "url": "^https?://(.*\\.)?craigslist\\.org.*",
    "pageElement": "css;ul.rows",
    "exampleUrl": "https://newyork.craigslist.org/search/zip",
    "useiframe": true,
    "autopager": {
        "newIframe": true,
     },
    "nextLink": "css;.bottom .next"
  }
```

It is documented here https://machsix.github.io/Super-preloader/siterule.html#rules-enhancements
> In addition to the basic elements, the rule can also contain an Object with key as autopager for enhanced functionality. autopager can contain the following key. All key are

**Comment by narcolepticinsomniac** [comment]
Aha, thanks.
