### ISSUE TITLE
好像论坛什么的没用

### ISSUE THREAD

**Issue by ldp00914** [machsix/Super-preloader#239]
https://bbs.3dmgame.com/forum.php?mod=viewthread&tid=5667691&extra=page%3D1%26filter%3Dtypeid%26typeid%3D30605

**Comment by ldp00914** [comment]
这是随便给个论坛链接

**Comment by kidonng** [comment]
请报告浏览器名称及其版本、脚本管理器及其版本、脚本版本，并打开脚本的调试模式，提交浏览器控制台的提示信息。 
另外 3DM 在我这边是可以自动翻页的。

**Comment by ldp00914** [comment]
> 请报告浏览器名称及其版本、脚本管理器及其版本、脚本版本，并打开脚本的调试模式，提交浏览器控制台的提示信息。
> 另外 3DM 等 Discuz 论坛在我这边是可以自动翻页的。

抱歉，安装了另一个浏览器下载插件对比了一下，可能是以前不小心把autopager改成preloader了，改回来好了，抱歉
