### ISSUE TITLE
和这个脚本冲突，导致3dm论坛失效，莫名其妙不知道为什么

### ISSUE THREAD

**Issue by ldp00914** [machsix/Super-preloader#240]
chrome81.0，tanpermonkey4.10
Super-preloader6.13.9
冲突脚本0.2.0  https://greasyfork.org/zh-CN/scripts/394216-%E7%BD%91%E7%9B%98%E9%93%BE%E6%8E%A5%E6%A3%80%E6%9F%A5
网站测试https://bbs.3dmgame.com/forum-2268-1.html

**Comment by machsix** [comment]
找那个脚本的作者去修复
