### ISSUE TITLE
悬浮窗的小点存在bug

### ISSUE THREAD

**Issue by heroboy** [machsix/Super-preloader#248]
1. 拖动的时候没有很好的跟随鼠标。
2. 鼠标一抖移动到屏幕外面就永远的跑出去了，因为点的位置被保存下来了。

**Comment by machsix** [comment]
https://github.com/machsix/Super-preloader/commit/b307d267df8ece6c5002c21badfe9c75b9f59664 里修了第一个，第二个没明白你啥意思，我没遇到过这种情况

**Comment by eth3lbert** [comment]
這邊反饋一個問題，
當有使用 vim-liked 的插件時 e.g. surfingkeys，
尋常操作就是 follow link，
b307d26 會造成浮動視窗擋住原有 element，
而被遮住的部分無法就不會產生 hint。

所以建議保留
```
spanel.style.display = 'block';

...

spanel.style.display = 'none';
```
這部分。

**Comment by heroboy** [comment]
@machsix 第二个的意思是，有时候由于某种bug，这个点的坐标会被计算成一个很大的值，这时候这个点在这个页面就永远看不见了。所以应该始终限制坐标的范围在屏幕内。
