### ISSUE TITLE
能去掉奇大无比的"iconv-browser","@sinonjs/text-encoding"模块吗？

### ISSUE THREAD

**Issue by heroboy** [machsix/Super-preloader#249]
唯一用到的地方是在got的时候，encode url。但是下一页的地址都是从页面上获取的，基本上已经url encode好了的。

**Comment by machsix** [comment]
不能，gmXmlRequest拿到的内容默认是utf8，要自己decode。fetch api之类的也一样。

**Comment by heroboy** [comment]
我就是没有找到你任何decode的地方才问的。

**Comment by machsix** [comment]
看上面的。

**Comment by heroboy** [comment]
而且现代浏览器都能用`TextDecoder`了，不用自己decode了。你已经用了Array.includes了，已经抛弃老的浏览器了吧。
@include http*的脚本，尽量优化一下吧。
https://github.com/machsix/Super-preloader/issues/238 的问题估计就是因为iframe太多了，载入脚本太慢了。

**Comment by heroboy** [comment]
我测试一下在firefox+tampermonkey，关闭所有规则。
打开example.com，如果开启这个脚本的话，大约需要额外多执行100ms的js时间。
所以，像mdn这种iframe很多的网站，卡死也是可能的。

**Comment by heroboy** [comment]
继续测试了一下，chrome+tampermonkey + example.com
页面载入完成之后，所有脚本执行时间：

* 不开启这个脚本：50ms
* 开启：200ms
* 开启了移除这个模块之后的版本（脚本大小变成一半）：170ms
