### ISSUE TITLE
Script is loaded in every iframe that embeds videos

### ISSUE THREAD

**Issue by LurkerHub** [machsix/Super-preloader#277]
On forum threads running on an SMF platform, youtube videos are loaded in iframes.  The script shows as loaded multiple times (for the main page and for each iframe)

I have manually excluded `https://www.youtube.com/embed/*` but I think it (and similar common embedding URLs) should be excluded by default since they have no "pages".

**Comment by machsix** [comment]
The script needs to be injected into the iframe as the `iframe mode` works by appending a iframe to the bottom of the page and loading the content of the next page. 
I will add this exclude into the next release

**Comment by LurkerHub** [comment]
That site works in the "normal" mode, not iframe.  The iframes I was talking about are a part of the original pages, and there is no need to inject anything into them as there is nothing to there to paginate.

Specifically, the script should be excluded from such embedding pages even when they are the top ones.

For example, see https://www.youtube.com/embed/M94yyfWy-KI

**Comment by alexolog** [comment]
Please also exclude https://assets.tumblr.com/* for similar considerations.

Thank you.
