### ISSUE TITLE
Two issues with tumblr

### ISSUE THREAD

**Issue by LurkerHub** [machsix/Super-preloader#278]
1) Does not work, the page separator is loaded on the right column.
Example: https://everythingfox.tumblr.com/

2) Need to exclude the following:
https://assets.tumblr.com/*
https://www.tumblr.com/video/*

**Comment by machsix** [comment]
<img width="607" alt="Capture" src="https://user-images.githubusercontent.com/28209092/98463266-e2325280-216e-11eb-9c58-35ab4d25043b.PNG">

Works here without adblocker and other scripts. Maybe it's the fault of your other script?

**Comment by LurkerHub** [comment]
I disabled all other add-ons and scripts.  The only thing left is Tampermonkey with the super-preloader script.  Problem still happens:

![image](https://user-images.githubusercontent.com/20542915/98471492-b8068200-21ba-11eb-8e1d-b3c86b1a2569.png)

**Comment by LurkerHub** [comment]
1. Running latest FF developers edition 83.0b9 (64-bit)
2. Created a new empty profile 
3. Installed Tampermonkey beta for FF from https://firefox.tampermonkey.net/firefox-current-beta.xpi
4. Installed script from https://machsix.github.io/Super-preloader/Super_preloaderPlus_one_New.user.js
5. Navigated to https://everythingfox.tumblr.com/

Problem still exists like the picture in my previous comment.

There is nothing else that can cause the problem.

**Comment by machsix** [comment]
Ok, I figured out. It's a bug of an upstream rule. I have fixed it http://wedata.net/items/681. You may need to click the "update rule" button to update the rules or wait for a day for the automatic update.

Any reason why the two links need to be excluded?
https://assets.tumblr.com/*
https://www.tumblr.com/video/*

**Comment by LurkerHub** [comment]
> Any reason why the two links need to be excluded?
> https://assets.tumblr.com/*
> https://www.tumblr.com/video/*

Due to #277

**Comment by machsix** [comment]
308b86f537ff05cb32d9c5bee3d51cf410870b99
