### ISSUE TITLE
Custom rule not working

### ISSUE THREAD

**Issue by LurkerHub** [machsix/Super-preloader#285]
The built-in rule rule img-hentai isn't very good.

I am trying to override it with a custom rule, but the built-in rule is still getting invoked on the exampleUrl.

Why?
```
{
  "name": "hentai-img",
  "exampleUrl": "https://hentai-img.com/image/jaycee-knight-bloomin-faeries-ongoing-1/page/1/",
  "url": "https://([^.]+\\.)?hentai-img\\.com/image/",
  "pageElement": "div[@id='display_image_detail']",
  "nextLink": "//div[@id='paginator']/span/a[(text()='Next>')]"
}
```

**Comment by machsix** [comment]
Your `pageElement` misses the double slash  `//div[@id='display_image_detail']`
Also your `nextLink` clearly doesn't capture any DOM element
<img width="707" alt="2020 6 22 2dwg" src="https://user-images.githubusercontent.com/28209092/86861111-498ea780-c094-11ea-8f3d-3f868735b98a.png">

In addition, add [NSFW] to the title and don't post an issue on both Github and Greasyfork
