### ISSUE TITLE
Navigation Bar Customization

### ISSUE THREAD

**Issue by brian6932** [machsix/Super-preloader#293]
Either a dark or mini/small navigation bar like the one that AutoPagerize uses, looks a lot better on websites with dark themes.

**Comment by machsix** [comment]
v6.15.1 introduced the function to define css of the appearance by yourself. For darkmode, you can simply add `.sp-separator {filter: invert(1.0)}`

**Comment by brian6932** [comment]
Where exactly do you insert that css?

**Comment by machsix** [comment]
`Gloabl settings` panel of the script

**Comment by brian6932** [comment]
Custom rules?

**Comment by machsix** [comment]
update to latest version https://greasyfork.org/en/scripts/33522-super-preloaderplus-one-new

**Comment by brian6932** [comment]
ohhhh, my bad
