### ISSUE TITLE
新版 6.6.33，添加 WordPress 强制规则后的bug

### ISSUE THREAD

**Issue by suchunchen** [machsix/Super-preloader#30]
由于 WordPress 的规则, 高级规则没有匹配会强制给出下一页的连接（xxxx/page/2）。
https://github.com/machsix/Super-preloader/blob/86ab4f6362c05e821a6231df0e95f1e4de238944/Super_preloaderPlus_one_New.user.js#L4872-L4890

导致这里直接绑定左右键的快捷键。
https://github.com/machsix/Super-preloader/blob/86ab4f6362c05e821a6231df0e95f1e4de238944/Super_preloaderPlus_one_New.user.js#L7632-L7641

疑问：

- 1.WordPress  到底是为了匹配什么页面，麻烦补充下 exampleUrl。或者补充下注释，说明那段强制返回的原因。
- 2.修复方案（2选一）：
1. 修改  WordPress  规则，
2. 检测到 nextlink 的 pageElement 没有值得时候，清空 nextlink的值。
https://github.com/suchunchen/Super-preloader/blob/8a5d0c399ea07eb75824f0082a6ae98bba1baaa5/Super_preloaderPlus_one_New.user.js#L7569-L7570

**Comment by machsix** [comment]
https://github.com/machsix/Super-preloader/commit/5641a44241460e166423c5dd3f8a480ef3f838d8
