### ISSUE TITLE
请问工作模式如何默认设置为自动翻页模式？

### ISSUE THREAD

**Issue by liangxyz** [machsix/Super-preloader#324]
如题，我在一个图片站里，没有更换网址的时候，是能正确自动翻页模式的。但是站点换了新网址，我发现脚本会自动变成预读模式，请问脚本的工作模式如何默认设置为自动翻页模式

**Comment by yfdyh000** [comment]
设置-自动翻页

**Comment by liangxyz** [comment]
> 设置-自动翻页

你好，自动翻页选项已经勾选，但是无效

**Comment by machsix** [comment]
一不提供网址，二不提供脚本版本，读懂https://greasyfork.org/zh-CN/scripts/33522-super-preloaderplus-one-new再来发issue
