### ISSUE TITLE
AdGuard兼容问题进展（来自AdGuard团队）

### ISSUE THREAD

**Issue by HITers2018** [machsix/Super-preloader#328]
之前提过这个兼容性问题，我同时也递交给了AdGuard团队，下面是他们给的结论以及临时解决方法：
this script uses the GM_registerMenuCommand method, which is removed from the GM API and therefore doesn't supported by AdGuard as we definitely explore modern and latest versions of well-known API. Nevertheless, we'll work on this issue and probably add this obsolete method's support in order to backward compatibility with the scripts like this.
As a temporary workaround, in order to make this script work please go to the "userscript" tab, click the gear icon near this script, select "edit" menu item. When the editor with the script data be open, please find and remove a further code snippet

          if (userLang === 'zh_CN') {

            //@ts-ignore

            //todo: patch the type

            GM.registerMenuCommand('Super_preloaderPlus_one_New 设置', setup);

          } else {

            //@ts-ignore

            GM.registerMenuCommand('Super_preloaderPlus_one_New Settings', setup);

          }  // 查找是否是页面不刷新的站点

结论就是AdGuard不支持GM_registerMenuCommand，很高兴AdGuard表示将会对其进行兼容，GM_registerMenuCommand
这个有替代吗？可否替换为新的API？
下面是AdGuard关于这个问题的链接：https://github.com/AdguardTeam/AdguardForWindows/issues/3421

**Comment by yfdyh000** [comment]
感觉可以用 https://github.com/greasemonkey/gm4-polyfill/blob/master/gm4-polyfill.js 提供支持

**Comment by machsix** [comment]
1. 新api`GM.xx`目前只有Greasemonkey 4在用，旧版api是`GM_xxx`，为Violentmonkey和Tampermonkey使用
2. 我的脚本是按照新版api写的，同时用polyfill实现了向前兼容https://greasyfork.org/en/scripts/373124-gm4-polyfill-mach6-legacy/code
3. `GM.xx`的api没有`registerMenuCommand`的功能，所以在polyfill里有以下这段代码https://github.com/machsix/Super-preloader/blob/4e735f6ef31100f587abc7429b8a8cea2a5b3620/polyfill/gm4-polyfill-mach6-legacy.js#L53-L82
4. 综合以上几点，如果你用的是Violentmonkey或Tampermonkey，`GM.registerMenuCommand`会被`GM_registerMenuCommand`替代。如果你用的是Greasemonkey 4，会被上面的代码替代，所以我无法理解他们给出的解释。

**Comment by machsix** [comment]
@HITers2018 
我刚意识到，你用adguard作为脚本管理器？

**Comment by HITers2018** [comment]
是的，虽然AdGuard没有油猴之类方便专业但是可以避开不能安装插件的限制，可以实现移动端浏览器的脚本注入，比如让移动端Chrome使用脚本，我觉得很有前景，这可以让脚本注入到几乎所有App中成为可能。

**Comment by machsix** [comment]
<img width="543" alt="Capture" src="https://user-images.githubusercontent.com/28209092/90679867-ac3b9d00-e215-11ea-8af2-d73d09f50cda.PNG">
@HITers2018  能提供一下你console log里关于Script Manager的信息吗？这样就可以选择性的决定是否GM_registerMenuCommand

**Comment by HITers2018** [comment]
好的，这是用AdGuard作为脚本管理器，访问百度时截的图。
![20200820_064856](https://user-images.githubusercontent.com/45704621/90697811-d17de900-e2b1-11ea-9011-b8b792319e7b.jpg)

**Comment by machsix** [comment]
https://github.com/machsix/Super-preloader/commit/1688c25c7cb5d81fc1fc7051c30ba0e7b3a7e332 改进了这个问题

发生这个问题的原因是别的脚本管理器都是直接把GM_xx函数inject到window里，而adguard extension把这几个argument pass了过去。
<img width="1173" alt="Capture" src="https://user-images.githubusercontent.com/28209092/90763748-1a2aa780-e29c-11ea-862d-dc18246a29ff.png">

然而目前对于某些网站比如Google还存在问题，表现为脚本无法拼接页面。造成这个问题的原因是adguard的GM_xmlhttpRequest拿到的并不是原始网页数据，目前无解。百度我试了没问题

PS：我只在电脑端测试了，不保证手机能用
