### ISSUE TITLE
Correct way to exclude parts of a site and entire sites

### ISSUE THREAD

**Issue by mustaqimM** [machsix/Super-preloader#360]
Hey there,

how do I assign excludes for certain sites and for subdomains of site?

I have it set up like so:
```
http*://*reddit.com/*,
http*://hn.premii.com/*,
paperspace.com,
localhost,
https://opengameart.org/*,
https://course.fast.ai/,
https://colab.research.google.com,
https://accounts.google.com/*
```

But this doesn't seem to work. For instance I want to exclude the entire site: `https://opengameart.org/`.
But I want it enabled on `github.com` but not on `https://github.com/login`:
![image](https://user-images.githubusercontent.com/24436622/91690071-ddd93000-eb54-11ea-82be-fb955ee53dea.png)

**Comment by machsix** [comment]
`https://opengameart.org/*` should do the trick. 

However, I don't suggest you to enable the following highlighted function. It's not well tested and may make website useless.

<img width="301" alt="Capture" src="https://user-images.githubusercontent.com/28209092/98636015-d794cc00-22da-11eb-9443-3d5ad7534c48.PNG">

A safer solution is to change the `Mode` from `Preloader` to `Autopager` and `save` it. If the webpage looks ok, continue use it.

<img width="310" alt="Capture" src="https://user-images.githubusercontent.com/28209092/98636227-496d1580-22db-11eb-9b1d-21894a0ac403.PNG">
