### ISSUE TITLE
【需求】用户自主选择UI

### ISSUE THREAD

**Issue by suchunchen** [machsix/Super-preloader#37]
http://bbs.csdn.net/topics/390244325
页面底部有评论，导致正文主体占比不正确
http://tv.duowan.com/1801/380717306538.html
同样的问题，侧边栏太长

是否开放 getRemain 中的占比？

**Comment by machsix** [comment]
好像已经修好了？

**Comment by suchunchen** [comment]
> 好像已经修好了？
看你半天没有回复这个issue，所以做了临时兼容。
页面url：http://tv.duowan.com/1801/380717306538.html
注释掉以下2个,就能重现了
[1](https://github.com/machsix/Super-preloader/blob/master/Super_preloaderPlus_one_New.user.js#L1936)
[2](https://github.com/machsix/Super-preloader/blob/master/Super_preloaderPlus_one_New.user.js#L1942)


另外，翻页的样式我觉得原来的好看，不要加个配置，让用户自己选择哪个样式？

**Comment by machsix** [comment]
原本也有这么想，不过我懒得弄了。。:sleeping:

如果有人有兴趣可以把这个commit的基础上改一改https://github.com/machsix/Super-preloader/commit/07dd975047ec24964094b6b185988d380fb5046f
