### ISSUE TITLE
规则求助， 网站：vis.10jqka.com.cn

### ISSUE THREAD

**Issue by dzki** [machsix/Super-preloader#373]
网址：https://vis.10jqka.com.cn/free/ybzx/index/
问题：无法翻页，只能显示翻2页，但其实2页的内容是相同的都为实际的第1页，在8月份还是好的，9月份更新后就出现问题了。请大神修正，不胜感激。
截图如下：
![20200907212153](https://user-images.githubusercontent.com/70899713/92392804-7113f600-f151-11ea-8a64-78c0d970f4ea.png)

**Comment by heroboy** [comment]
我不知道url应该设置成什么。但是你可以试试：
```js
{
    url:"https://vis.10jqka.com.cn/free/ybzx/index/ctime/-3/pageNum/649/curPage/1",
    nextLink:"css;a[class='cur']+a",
    pageElement:"css;#commonTable"
}
```

**Comment by dzki** [comment]
@heroboy 感谢大神回复。
第一页的网址是：https://vis.10jqka.com.cn/free/ybzx/index/title/%E8%B6%85%E9%A2%84%E6%9C%9F/ctime/-3/doSearch/1/pageNum/28/curPage/1
试了下将url改为这个后可以翻页了，非常感谢帮助。
现在还想请教下，可以翻页后中间分隔位置的页码没有了，以前翻页后是有的，这个网站设计比较奇葩，只能10页10页的显示，所以页码还是有一定的参考，大神能否改改让页码显示出来？我是代码小白，有说的不对的还请见谅。
现在翻页后的效果见下图：
![20200915195739](https://user-images.githubusercontent.com/70899713/93208142-ae4e3880-f78e-11ea-8ace-e494ae339b86.png)
想要显示的页码见红色圈处：
![20200915195824](https://user-images.githubusercontent.com/70899713/93208185-c45bf900-f78e-11ea-9ce5-c25cf1659e73.png)

先谢过了。

**Comment by heroboy** [comment]
把pageElement改成：
```
pageElement:"css;.main"
```

**Comment by dzki** [comment]
@heroboy 非常感谢，完全OK了，谢谢帮助！

**Comment by dzki** [comment]
已经解决，感谢大神帮助！ @heroboy
