### ISSUE TITLE
bluemoonroleplaying.com forum (xenforo) failes on some threads [NSFW]

### ISSUE THREAD

**Issue by LurkerHub** [machsix/Super-preloader#374]
**Edit**: 
This only happens on threads that have exactly one post on their last page.  That last page will not load.
I changed the "bad" link since the previous one got another post in it and no longer fit the test case.

**Describe the bug**
https://bluemoonroleplaying.com/community/threads/98986/ -- works
https://bluemoonroleplaying.com/community/threads/113157/ -- does not work

**To Reproduce**
1. Go to url: https://bluemoonroleplaying.com/community/threads/113157/
2. Scroll down to bottom of page
3. Next page not loaded

**Expected behavior**
Next page should be loaded

**Desktop (please complete the following information):**
 - Firefox dev 81.0b9 (64-bit)
 - Tampermonkey 4.11.6119
 - Ublock Origin
 - Script version: 6.15.4

**Comment by cordear** [comment]
![image](https://user-images.githubusercontent.com/42716133/93290847-3cb8cd80-f814-11ea-9447-ad0cbd8fe87f.png)
on my browser(edge 87 with ublock origin), it works fine.

**Comment by LurkerHub** [comment]
Hmmm...  It works again now.  Probably FF messed something in one of the betas.  Closing.

**Comment by LurkerHub** [comment]
Reopening.

I think I figured out what is happening.

If the next page has **exactly one post** in it, then than page won't load.  Otherwise, if it has two or more posts, it will.

The problem is that it catches you by surprise.

@cordear, can you please try to reproduce?

**Comment by cordear** [comment]
It seems a general rule causes that problem.
I have written a specific rule for the website:
```javascript
{
    "name": "Blue Moon Roleplaying",
    "url": "^https?://bluemoonroleplaying\\.com/community/*",
    "pageElement": "//*[@class='block-container lbContainer']",
    "nextLink": "//li[contains(@class,'current')]/following-sibling::li[1]/a"
}
```
I have tried this rule in some threads, it works great.
I will open a pull request for this later.

**Comment by LurkerHub** [comment]
The best solution IMHO would be to fix the general rules since there are other sites that exhibit the same behaviour.

For example [SFW]:
https://xenforo.com/community/threads/job-xf-emailunsubscribe-invalid-header-value-detected.177611/

**Comment by LurkerHub** [comment]
Here's my suggestion:
```
{
  "name": "XenForo thread",
  "url": "^http(s)?://.+/community/",
  "exampleUrl": "https://xenforo.com/community/threads/job-xf-emailunsubscribe-invalid-header-value-detected.177611/",
  "pageElement": "//div[@class='block-container lbContainer']",
  "nextLink": "//a[@class='pageNav-jump pageNav-jump--next']"
}
```
Comments?


These are my custom rules for various forums:
```
[{
  "name": "SMF search",
  "url": "http(s?)://.+/index\\.php\\?",
  "exampleUrl": "https://elliquiy.com/forums/index.php?action=profile;area=showposts;u=37215",
  "pageElement": "//div[@class='pagesection'][1]/..",
  "nextLink": "//div[@class='pagesection'][2]//strong/following-sibling::a[@class='navPages'][1]"
},{
  "name": "PhpBB thread",
  "url": "http(s?)://.+/viewtopic\\.php\\?f=\\d+&t=\\d+",
  "exampleUrl": "https://eztech.transtar1.com/viewtopic.php?f=31&t=1327",
  "pageElement": "//div[@id='page-body']",
  "nextLink": "//a[@rel='next']"
},{
  "name": "Kronos forum",
  "url": "http(s?)://.+/t5/",
  "exampleUrl": "https://productioncommunity.publicmobile.ca/t5/Plans-Add-Ons/Share-Your-3G-Real-World-Experience/td-p/174940",
  "pageElement": "//div[@id='messageList' or @class='linear-message-list message-list']",
  "nextLink": "//a[@rel='next']"
},{
  "name": "XenForo thread",
  "url": "^http(s)?://.+/community/",
  "exampleUrl": "https://xenforo.com/community/threads/job-xf-emailunsubscribe-invalid-header-value-detected.177611/",
  "pageElement": "//div[@class='block-container lbContainer']",
  "nextLink": "//a[@class='pageNav-jump pageNav-jump--next']"
}]
```

**Comment by cordear** [comment]
The general rule which has a little problem is:
```
(//article[not(contains(../@class,'widget'))][not(contains(@class,'columns four'))][not(ancestor::*[starts-with(@class,'sidebar')])]|//*[starts-with(@id,'post-')][not(contains(@id,'post-rating'))])[not(.//*[contains(@class,'admz')])][not(id('load-more-posts') or @id='fpost' or contains(@class,'carousel'))][parent::node()[not(self::h2)][not(@id='side')][not(contains(@class,'thumbnail'))][not(following-sibling::*[not(@id='side')][article or *[starts-with(@id,'post-')]])]/*[self::article or starts-with(@id,'post-')]/following-sibling::*[self::article or starts-with(@id,'post-')][not(contains(@id,'nav'))]]|id('content')[count(div)>1]/div[contains(@class,'post')][not(contains(div/@class,'breadcrumb'))][not(contains(div/@class,'nav'))]
```
I think the problem is in the `parent::node()` part.
I have made a small change:
```
(//article[not(contains(../@class,'widget'))][not(contains(@class,'columns four'))][not(ancestor::*[starts-with(@class,'sidebar')])]|//*[starts-with(@id,'post-')][not(contains(@id,'post-rating'))])[not(.//*[contains(@class,'admz')])][not(id('load-more-posts') or @id='fpost' or contains(@class,'carousel'))][parent::node()[not(self::h2)][not(@id='side')][not(contains(@class,'thumbnail'))][not(following-sibling::*[not(@id='side')][article or *[starts-with(@id,'post-')]])]/*[self::article or starts-with(@id,'post-')][following-sibling::node()[self::article or starts-with(@id,'post-')][not(contains(@id,'nav'))] or not(following-sibling::*)][parent::*[not(contains(@class,'userContent'))]]]|id('content')[count(div)>1]/div[contains(@class,'post')][not(contains(div/@class,'breadcrumb'))][not(contains(div/@class,'nav'))]
```
I haven't tested it fully yet.
But on the website which you listed above, it seems to work correctly.

**Comment by machsix** [comment]
cordear's PR seems to fix this problem. But I still add LurkerHub's rule to the general rule list since it's a different CMS.

LukerHub: PR is welcome if  https://whatcms.org/ finds the website use a specific CMS. Please modify this file https://github.com/machsix/Super-preloader/blob/master/src/rules/jsGeneralRule.js

As most websites require account to view the content..I'm too lazy to register one

**Comment by LurkerHub** [comment]
https://github.com/machsix/Super-preloader/pull/431
