### ISSUE TITLE
Breaks Paypal Log In page

### ISSUE THREAD

**Issue by brian6932** [machsix/Super-preloader#398]
The sign in page will seem relatively normal, however, with this script enabled it causes the page to error once signing in with the correct credentials, it also breaks PayPal's captchas.

1. Go to url: 'https://www.paypal.com/signin' 
2. Enter credentials/captchas

 - Browsers [Chrome, Firefox]
 - Versions [85, 68]
 - Script Manager [Violentmonkey]
 - Adblocker [Ublock Origin]
 - Script version: 6.15.4

**Comment by brian6932** [comment]
How do you disable specifics sites using Super-preloader?

**Comment by brian6932** [comment]
I managed to figure out how to use the exclude function which fixes the issue:
// @exclude      https://www.paypal.com/*

**Comment by machsix** [comment]
fixed, thanks for the feedback
