### ISSUE TITLE
无限翻页问题

### ISSUE THREAD

**Issue by Kapsugar** [machsix/Super-preloader#41]
建议在Greasyfork的页面的第6200行下面加上
a_ipages_1 = a_ipages_1 == "" ? 0 : a_ipages_1 ;

差不多这样改一下就可以了吧....大概(大雾)

**Comment by Kapsugar** [comment]
有的时候不知道怎么回事,这个a_ipages_1 值可能会空值,然后就导致无限翻页的情况

**Comment by machsix** [comment]
举个🌰?

**Comment by Kapsugar** [comment]
....不是,是你把这个判断给加上去,应该就可以了,我看Greasyfork上面有不少人说这个问题,差不多应该就是这个,现在不知道什么情况,会出现下面这个框里面的值会便成空,而且能够被执行.
这个标签对应的ID是`a_ipages_1` ,我看脚本取值差不多是第6200行上面的那一块进行的取值,所以在上面加一个三目判断,如果为空强制改成0,就是不翻页,或者改成1也可以,后面的代码我没看,我不知道后面的逻辑是怎样写的,如果逻辑没问题,按照上面的改成0就行了,如果0页逻辑会有问题的话,那就只能改成1咯.

然后就是这一段咯,位置大概就是6200行左右
`a_ipages_1 = a_ipages_1 == "" ? 0 : a_ipages_1 ;`

![QQ截图20190507093113](https://user-images.githubusercontent.com/26645070/57265894-453fb680-70ac-11e9-8b39-a05a00fe4913.png)
![QQ截图20190507094345](https://user-images.githubusercontent.com/26645070/57265994-a2d40300-70ac-11e9-935d-9db5cf76ce48.png)

**Comment by Kapsugar** [comment]
不对 这么改也不对.....上面的const的变量是不可变的.......傻逼了傻逼了

**Comment by Kapsugar** [comment]
`a_ipages_1`是`const`变量,昨天没仔细看就随口说了,今天一早回来又看了一遍代码,发现这么改有问题的.....我脑子抽了(捂脸滑稽.JPG).

还是来张图比较直接把.

就是在火狐和谷歌里面,有几率有的时候会出现这种情况,尽管确实里面是写死了最小值是1,但是仍然有的时候会变成空,也就是"",然后就...无限翻页了,我估计原来Greasyfork很多人反馈的都是这个问题.
![QQ截图20190507143347](https://user-images.githubusercontent.com/26645070/57276894-6f599e80-70d5-11e9-80db-3700e07f4288.png)

我对这个脚本究极怎么取已经保存的值也不熟悉,所以就算刚刚那个`a_ipages_1`不是`const`变量,但是改那个地方也是不对的....我觉得改的话,是改取保存好的值的地方,然后看看取出来的是不是""如果是""就强制改成1.

我觉得差不多就是这样吧.(大雾)

**Comment by machsix** [comment]
虽然写了`min`但实际没有调用。。:cry:
