### ISSUE TITLE
High CPU on scroll

### ISSUE THREAD

**Issue by narcolepticinsomniac** [machsix/Super-preloader#435]
Cent Version 4.3.9.182 (Official Build) (64-bit) (Portable) (Chromium 86.0.4240.183)
Super_preloaderPlus_one_New 6.15.8
TamperMonkey Beta

CPU spikes for a few seconds are expected when loading new content, but on [this site](https://moviesverse.com/), they appear to occur on every little scroll in either direction.

**Comment by machsix** [comment]
not reproducible on firefox+violentmonkey. I don't care about chromium, especially third-party mod
