### ISSUE TITLE
Need fix for Royal Road, custom rules is impossible to figure out, please implement drag n drop.

### ISSUE THREAD

**Issue by DefectiveByDesign** [machsix/Super-preloader#468]
Need fix for Royal Road, custom rules is impossible to figure out due to documentation that non-programmers cannot understand. Also, it would be massively easier to implement a custom rule if the script worked with drag n drop or copy-paste.

Here's some of the code for the next chapter, but I cannot figure out how to write code for it, if anyone else knows.
a.col-xs-4:nth-child(3)
a.btn.btn-primary col-xs-4  (?)
btn btn-primary col-xs-4
/html/body/div[3]/div/div/div/div/div[4]/div[2]/div[1]/div[2]  (top)
/html/body/div[3]/div/div/div/div/div[4]/div[2]/div[5]/a[3]   (bottom)
Button name is "Next Chapter" which the name might be throwing off the auto mode.
I've tried copy pasting spliced example code into the custom rules, but it doesn't work.  I also don't understand the "pageElement" variable, because it seems only necessary for scrollable websites like google search, or it refers to the actual button element, but the documentation is too vague for a non-programmer who has no idea what these variables are or how to write them.

Here's an example link if you need one, and it is SFW, pure text novel.
https://www.royalroad.com/fiction/22518/chrysalis/chapter/321896/chapter-1-anthony-reborn

**Comment by Killogy** [comment]
@DefectiveByDesign

```
     {name: 'royalroad', 
      url: 'https?://www\.royalroad\.com', 
       nextLink: '//a[contains(text(),"Next")]', 
      pageElement: '//div[@class="chapter-inner chapter-content"]'
}
```

**Comment by DefectiveByDesign** [comment]
I'm not sure if I copied it wrong, have issue with spacing, or put it in the wrong spot, but it doesn't work. Could even be a browser bug, or issue with violent monkey, and I need to use tampermonkey. I'll mess around with it more just in case, and try tampermonkey.

There's another script that is for hotkeys, but the code is so much different. Simple enough that I can understand it, but it doesn't translate to this script.
https://greasyfork.org/en/scripts/373923-royalroad-hotkeys

**Comment by Killogy** [comment]
My script is working properly with Greasemonkey 3 and ViolentMonkey.  

Scripts must be between [ ] so make sure there is a [ at beginning and a ] at the end of the scripts list you have added.

Super preloader settings for specific website are stored in cookies LOCAL STORAGE (visit a website and open Devtools by pressing key combination CONTROL+SHIFT+I or press-and-hold/right-click an item on a webpage and choose Inspect Element from the context menu that appears) then expand tree LOCAL STORAGE and select the website item, on the right you will find a cookie named **spfwset** there is the Super preloader settings when you manually has enabled it for that specific website.

So deleting the cookie **spfwset** you will reset Super preloader settings for that specific website when you manually has enabled it.

**Comment by DefectiveByDesign** [comment]
Thanks dude, you're a genius at this stuff! I wouldn't have figured it out otherwise. Well, I did figure out the brackets, but that was more random trying things than understanding what I was doing.

 Is there any reading material you could recommend for learning some of this stuff? Not to be a professional, but something that explains enough of the basics that I'm not completely lost. I kinda want to learn how that tiny excerpt works.

**Comment by Killogy** [comment]
Everything about custom rules is here https://machsix.github.io/Super-preloader/siterule.html

Here the list of custom rules Super preloader is using https://github.com/machsix/Super-preloader/blob/master/dist/mydata.json
