### ISSUE TITLE
能支持白名单吗？

### ISSUE THREAD

**Issue by chaofengxn** [machsix/Super-preloader#53]
不是所有网站都需要翻页的

**Comment by machsix** [comment]
![1](https://user-images.githubusercontent.com/28209092/58344570-0e93cb00-7e24-11e9-811e-a33d71906547.PNG)
这汉字写的挺清楚吧

**Comment by chaofengxn** [comment]
谢谢，不好意思没看到

**Comment by chaofengxn** [comment]
我是希望刚开始在所有网页不启动，然后进入论坛等需要翻页的网页手动添加，毕竟不需要翻页的网站居多，可能是我没表达清楚

**Comment by heroboy** [comment]
@machsix 这个虽然已经关闭了。但是我还是要说，能不能默认关闭所有内置规则。我希望我第一次访问网站的时候是原版的网站，而不是被这个userscript“破坏”过的样子。等熟悉了之后再决定要不要开启。

**Comment by machsix** [comment]
那你直接关掉脚本就得了呗。。油猴脚本没有访问你历史记录的权限，虽然可以通过localstorage记录，我没这个需求。你可以pr
