### ISSUE TITLE
[NSFW]https://lovens.cc 翻页无法使用

### ISSUE THREAD

**Issue by kidzgy** [machsix/Super-preloader#567]
例子：https://lovens.cc/2021/04/13/albumxiuren%E5%91%A8%E4%BA%8E%E5%B8%8Cno-32742021-04-13/

这个翻页规则比较棘手，页码没有看到“下一页”类似的字样，而且页码href是“javascript:void(0)”这样的。
即便是手动翻页，翻的下一页会覆盖当前页内容。

**Comment by machsix** [comment]
lazyload 没办法
