### ISSUE TITLE
Infinite paging on single page WordPress site

### ISSUE THREAD

**Issue by kidonng** [machsix/Super-preloader#58]
Site: https://www.myconan.net/
There's only a landing page on this site, but the script will keep loading the next page.
Pagination can be an identifier for this case, but it can vary from site to site. 

---

This problem happens on [GitHub Blog](https://github.blog/2010-11-13-sidejack-prevention-phase-3-ssl-proxied-assets/) as well.

---

Well, this can happen **anywhere**, I can't number them all, so basically the best solution is to blacklist those sites?

**Comment by machsix** [comment]
Both websites are built with WordPress. The default next page in WordPress is currentLink+/page/2.

For [Github Blog](https://github.blog/2010-11-13-sidejack-prevention-phase-3-ssl-proxied-assets/), I fixed it in https://github.com/machsix/Super-preloader/commit/13ebe3b5aad4ce468c5343b84b42b83c7629bc61 by comparing the finalURL in the response to the URL of the current page.

However, the method doesn't work for https://www.myconan.net/. I have also tried to compare the returned HTML body with the current page by [isEqualNode](https://developer.mozilla.org/en-US/docs/Web/API/Node/isEqualNode) but it always returns `false`. 

So you may need to add the website to blacklist for wordpress https://github.com/machsix/Super-preloader/blob/78d7d4ef66a1f2e8b6d776d1cd6188bfd9a67abf/Super_preloaderPlus_one_New.user.js#L1466

**Comment by kidonng** [comment]
Well, that's why blacklist exists. Thanks for looking into this!

**Comment by kidonng** [comment]
https://github.blog/2019-08-15-commit-signing-support-for-bots-and-other-github-apps/?utm_campaign=1565898720&utm_medium=social&utm_source=twitter&utm_content=1565898720

Still loading if the page has search params.

**Comment by kidonng** [comment]
Seems like the problem has been resolved.
