### ISSUE TITLE
百度搜索特定文字时搜索结果会被框选，然后点击会跳转到其百科页面。

### ISSUE THREAD

**Issue by openipka** [machsix/Super-preloader#620]
**Describe the bug**
百度搜索特定文字时搜索结果会被框选，然后点击会跳转到其百科页面。(文中以10010举例）

**To Reproduce**
1. Go to url: https://www.baidu.com/s?ie=UTF-8&wd=10010

**Expected behavior**
这个框导致完全无法查看搜索结果，而正常应该是可以看的。

**Screenshots**
![2021-06-30_211406](https://user-images.githubusercontent.com/78248875/123967019-84e25e80-d9e8-11eb-84e5-4b0ca1c4291c.png)
这是开启SuperPreloader的情况
![2021-06-30_211634](https://user-images.githubusercontent.com/78248875/123967171-a5aab400-d9e8-11eb-8134-bcd97b6c3333.png)
这是关闭SuperPreloader的情况

**Desktop (please complete the following information):**
 - Chrome
 - Version 73.0.3683.103
 - Tampermonkey
 - Ublock Origin
 - Script version: v6.15.9

**Additional context**
 - Have you tried to reset the script following [link](https://greasyfork.org/en/scripts/33522-super-preloaderplus-one-new/discussions/33898) [Yes]

**Comment by GoogleBeEvil** [comment]
可以复现，百度致钛 SC001,贴吧那个链接直接变成百科了

**Comment by GoogleBeEvil** [comment]
度娘整的幺蛾子  ，在搜索结果上面加了个透明遮罩，ublock加入下列规则即可www.baidu.com##.c-img-radius-large.c-img-border

**Comment by 6Tom** [comment]
楼上说得对，可能是百度出的反制措施，如果出现的话，用ublock吸管吸两次，即可把两层透明遮罩吸掉，此后可以始终防范

**Comment by machsix** [comment]
临时修复：https://github.com/machsix/Super-preloader/commit/31c3e1395174df2a88aaca71c796fe65e4522b7d
推荐办法：安装ublock origin并订阅CHN: AdGuard Chinese (中文)
