### ISSUE TITLE
google搜索 "血肉苦弱"，下滑翻页会出现排版/链接问题，其他关键字就不会..

### ISSUE THREAD

**Issue by tooyangtoonaive** [machsix/Super-preloader#710]
vivaldi 2.10.1745.27 (相当于chrome 79.0.3945.131) + Tampermonkey 4.13

1.google搜索 "血肉苦弱" (https://www.google.com/search?q=血肉苦弱)
2.下滑直到自动翻页
3.排版错误，此时任意点击会进入一个错误的页面

刚打开网页：
![image](https://user-images.githubusercontent.com/19810827/144708149-5e45479e-40e5-4c35-bd73-f84365b29fe0.png)

下滑直到自动翻页:
![image](https://user-images.githubusercontent.com/19810827/144708160-ef0470e4-a273-46f1-a455-8b37d0b50e4d.png)

再翻回去：
![image](https://user-images.githubusercontent.com/19810827/144708200-10bf6ca4-1097-4ac7-9f92-f41e74fbb9c0.png)

**Comment by GanZhiXiong** [comment]
Google 随便搜索出来的结果，点击链接会进入不正确的页面。而且搜索第一条结果的链接会重叠模糊。
![image](https://user-images.githubusercontent.com/27394631/145746249-802faea8-a8d4-40eb-8700-148ce692f880.png)

这个问题比较严重 @machsix

**Comment by mpc2008cn** [comment]
搜索NCPD也会出现此现象
![image](https://user-images.githubusercontent.com/11917818/156091657-35ff80e6-6e74-4738-90ae-f4116764bddb.png)
