### ISSUE TITLE
wedata.net connections

### ISSUE THREAD

**Issue by 07416** [machsix/Super-preloader#755]
Is it mandatory to connect to a (Chinese-owned) third-party domain as a core function of this script? 

Seems to have a potential to occur hundreds of times a day.

**Comment by machsix** [comment]
First, wedata.net is a Japanese-owned domain, although it shouldn't matter who owns it
Second, this script originates from http://wedata.net/databases/AutoPagerize/items and still uses site rules there. I would say 90% of rules come from that site.
Third, if the script runs normally, it should only update rules once every day. 100 times a day means some issue on your side
